### ISSUE TITLE
Mismatch in transition probability

### ISSUE THREAD

**Issue by dvklopfenstein** [pwac092/gossto#5]
Hello,

Thank you so much for making the GOssTo Java code easy to compile and run. The paper is wonderful and the code is implemented so beautifully.

## Description
I am working through the example in the [paper](https://www.ncbi.nlm.nih.gov/pubmed/22522134) described in figure 2a and am seeing a mismatch for one of the *transition probability values*, C->A, seen from the output of GOssTo and the values shown in the figure where the mismatches are marked:
  * **ACT**: Actual values calculated with GOssTo
  * **EXP**: Expected values seen in the paper 

## Test
Notes:
1. I had to rename the files with a .txt extension to get them to load into GitHub.    
2. Please note I swapped nodes F and G so the plot would look nicer. 
3. The transition probability for B->A matches the expected value.
4. I get the transition probability values by adding a print statement in the code:
    *src/ISM_ImplementationStrategies/ISM_validImplementation.java*::walk()
    `P.print(10, 6);` 

[fig2a.gaf.txt](https://github.com/pwac092/gossto/files/3664715/fig2a.gaf.txt)    
[fig2a.obo.txt](https://github.com/pwac092/gossto/files/3664716/fig2a.obo.txt)    
[fig2a.mk.txt](https://github.com/pwac092/gossto/files/3664725/fig2a.mk.txt)    

![yang_fig2a_small](https://user-images.githubusercontent.com/7278188/65806050-e4497580-e155-11e9-811d-6d06085a2d30.png)

**Comment by dvklopfenstein** [comment]
Hi, never mind. Your code works perfectly. I was looking at the transition edge for Ua->A.

The probability transition from C->A matches perfectly in the paper.

LOVE your paper and this code. You did a fantastic job.

**Comment by pwac092** [comment]
Dear DV,

Sorry for the late reply. I am happy you managed to sort it out :). Please
do not hesitate to contact me if you have any questions.

Kind Regards.

Horacio Caniza
